"""Export helpers for OpenSCAD source code."""

from __future__ import annotations

import logging
import re
from datetime import datetime, timezone

logger = logging.getLogger(__name__)

FREECAD_HEADER = (
    "// Generated by OpenSCAD Playground – optimized for FreeCAD import\n"
    "// Date: {date}\n"
    "// Ensure ASCII-only characters for maximum compatibility.\n\n"
)


class ExportService:
    """Prepare OpenSCAD source code for download or FreeCAD interop."""

    def format_scad(self, code: str, *, optimize_for_freecad: bool = False) -> tuple[str, str]:
        """Return *(formatted_code, suggested_filename)*."""
        if optimize_for_freecad:
            code = self._optimize_for_freecad(code)
            filename = self._generate_filename(prefix="freecad_export")
        else:
            filename = self._generate_filename(prefix="openscad_export")

        return code, filename

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    @staticmethod
    def _optimize_for_freecad(code: str) -> str:
        header = FREECAD_HEADER.format(date=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"))
        ascii_code = code.encode("ascii", errors="replace").decode("ascii")
        # Normalise inconsistent line endings
        ascii_code = ascii_code.replace("\r\n", "\n")
        return header + ascii_code

    @staticmethod
    def _generate_filename(prefix: str) -> str:
        ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        return f"{prefix}_{ts}.scad"
